stages:
  - test
  - build
  - manifest

include:
  - project: code0-tech/development/telescopium
    ref: build-branch
    file: ci-template.gitlab-ci.yml

.dind:
  variables:
    DOCKER_MIRROR: https://mirror.gcr.io
    DOCKER_OPTIONS: "--registry-mirror ${DOCKER_MIRROR}"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: /certs
  services:
    - name: docker:29.4.1-dind
      alias: docker
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_OPTIONS" ]

.node-actions:
  - gls-action
  - shopify-action
  - woocommerce-action
  - shopware-action
  - twilio-action
  - stripe-action

.rust-actions:
  - cron-action
  - rest-action
  - mcp-action

test-node:
  image: node:24.10.0
  stage: test
  parallel:
    matrix:
      - C0_ACTION: !reference [.node-actions]
  script:
    - cd actions/$C0_ACTION
    - npm ci
    - npm run typecheck
    - npm run test

build-docker:
  extends:
    - .dind
  image: docker:29.4.1
  stage: build
  tags:
    - c0-$PLATFORM
  parallel:
    matrix:
      - C0_ACTION: !reference [.node-actions]
        PLATFORM: [amd64, arm64]
      - C0_ACTION: !reference [.rust-actions]
        PLATFORM: [amd64, arm64]
  before_script:
    - echo $C0_GH_TOKEN | docker login -u $ --password-stdin ghcr.io
    - docker context create build-context
    - docker buildx create --name container-builder --driver docker-container --bootstrap --use build-context
  script:
    - cd actions/$C0_ACTION
    - >
      docker buildx build
      -t ghcr.io/code0-tech/centaurus/ci-builds/$C0_ACTION
      --output type=registry,push-by-digest=true
      --metadata-file manifest-${CI_JOB_ID}.json
      .
  artifacts:
    paths:
      - actions/$C0_ACTION/manifest-*.json
    expire_in: 1 day

manifest-docker:
  extends:
    - .dind
  image: docker:29.4.1
  stage: manifest
  tags:
    - c0-amd64
  parallel:
    matrix:
      - C0_ACTION: !reference [.node-actions]
      - C0_ACTION: !reference [.rust-actions]
  needs:
    - job: build-docker
      parallel:
        matrix:
          - C0_ACTION: [ '$[[ matrix.C0_ACTION ]]' ]
            PLATFORM: [amd64, arm64]
  before_script:
    - apk add --no-cache jq
    - echo $C0_GH_TOKEN | docker login -u $ --password-stdin ghcr.io
  script:
    - cd actions/$C0_ACTION
    - |
      refs=""
      for manifest in manifest-*.json; do
        name=$(jq -r '."image.name"' "$manifest")
        digest=$(jq -r '."containerimage.digest"' "$manifest")
        refs="$refs $name@$digest"
      done
      docker buildx imagetools create -t "ghcr.io/code0-tech/centaurus/ci-builds/$C0_ACTION:0.0.0-experimental-$CI_PIPELINE_ID-$CI_COMMIT_SHA" $refs
