version: "3.9"

services:
  gls-action:
    build:
      context: .
      dockerfile: actions/gls-action/Dockerfile
    container_name: gls-action
  ai-action:
    build:
      context: .
      dockerfile: actions/ai-action/Dockerfile
    container_name: ai-action
