import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { buildGenerator, getProgramFromFiles } from "typescript-json-schema";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const sdk = JSON.parse(readFileSync(require.resolve("@notionhq/client/package.json"), "utf8"));
const aliases = resolve(root, "schemas/notion-types.ts");
const roots = [...readFileSync(aliases, "utf8").matchAll(/export type (Notion\w+)\s*=/g)].map((match) => match[1]);
const program = getProgramFromFiles([aliases], { strictNullChecks: true, skipLibCheck: true }, root);
// Keep generic aliases expanded: aliasRef would turn nested Record<K, V>
// instances into a reference to the unspecialized (empty) Record definition.
const generator = buildGenerator(program, { required: true, ref: true, aliasRef: false, topRef: true });
if (!generator) throw new Error("Could not compile the official Notion SDK types.");
// typescript-json-schema drops the `never` index signature of the SDK's
// EmptyObject. Preserve its actual meaning: no keys are allowed.
generator.setSchemaOverride("EmptyObject", { type: "object", additionalProperties: false });
const jsonSchema = generator.getSchemaForSymbols(roots);

// JSON Schema draft-07 definitions map directly to OpenAPI 3.1 components.
// Normalize compiler-derived names to stable names supported by our shared
// generator, preserving every reference and nullable/union/recursive shape.
const definitions = jsonSchema.definitions ?? {};
const names = new Map(Object.keys(definitions).sort().map((name) => [name, name.replace(/[^a-zA-Z0-9_]/g, "_")]));
if (new Set(names.values()).size !== names.size) throw new Error("OpenAPI component name collision.");
function normalize(value) {
    if (Array.isArray(value)) return value.map(normalize);
    if (value && typeof value === "object") {
        return Object.fromEntries(Object.entries(value).filter(([key]) => key !== "$schema").map(([key, entry]) => {
            if (key === "$ref") {
                const name = decodeURIComponent(entry.replace(/^#\/definitions\//, "")).replace(/~1/g, "/").replace(/~0/g, "~");
                if (!names.has(name)) throw new Error(`Unresolved reference: ${entry}`);
                return [key, `#/components/schemas/${names.get(name)}`];
            }
            return [key, normalize(entry)];
        }));
    }
    return value;
}
const schemas = Object.fromEntries([...names].map(([name, normalized]) => [normalized, normalize(definitions[name])]));
for (const name of roots) if (!schemas[name]) throw new Error(`Missing root schema: ${name}`);
const spec = {
    openapi: "3.1.0",
    info: {
        title: "Notion action schemas", version: "2022-06-28",
        description: `Generated from @notionhq/client ${sdk.version}. The public Notion MCP OpenAPI spec lacks complete response schemas; these components are derived from the official SDK instead. Do not edit by hand.`,
        license: { name: "MIT", url: "https://github.com/makenotion/notion-sdk-js/blob/main/LICENSE" },
    },
    "x-source": { package: sdk.name, version: sdk.version, aliases: "schemas/notion-types.ts" },
    paths: {},
    components: { schemas },
};
mkdirSync(resolve(root, "schemas"), { recursive: true });
writeFileSync(resolve(root, "schemas/notion-openapi.json"), JSON.stringify(spec, null, 2) + "\n");
// Register shared components before their consumers so Hercules exports named
// references instead of repeatedly expanding the full Notion object graph.
const order = [];
const visited = new Set();
function visit(name) {
    if (visited.has(name)) return;
    visited.add(name);
    for (const match of JSON.stringify(schemas[name]).matchAll(/"\$ref":"#\/components\/schemas\/([^"]+)"/g)) visit(match[1]);
    order.push(name);
}
for (const name of Object.keys(schemas).sort()) visit(name);
mkdirSync(resolve(root, "src/generated"), { recursive: true });
writeFileSync(resolve(root, "src/generated/notion-schema-order.ts"),
    "// AUTO-GENERATED by scripts/generate-openapi.mjs. Do not edit.\n" +
    `export const supportingSchemaNames = ${JSON.stringify(order.filter((name) => !roots.includes(name)), null, 2)} as const;\n`);
console.log(`Generated ${names.size} OpenAPI components from ${sdk.name}@${sdk.version}`);
